### PR TITLE
Dombranch

### PR DESCRIPTION
**Pull request by DomenicoDicosimo**
Created the basic backend functionality and tied in Firebase with react hooks.
we can use this as a baseline to build out the different chat rooms and user profile etc
there is no frontend yet, so alot of work to be done there!

### CODE REVIEW

**Review by ksantos1997 — APPROVED** [review]
Good

**Review by ksantos1997 — APPROVED** [review]
Good

**Review by eganokumugit — APPROVED** [review]

**Review by eganokumugit — APPROVED** [review]
Looks good

**Comment by acua22** [comment]
nice

**Pull request merged**
